import { NextResponse } from "next/server";

export async function GET() {
  const content = `# BUSINESS.IN — AI Location Decision Simulator

BUSINESS.IN is an interactive AI-powered decision simulation engine for commercial real-estate and business location strategy in Bengaluru, India.

## 🎯 Platform Overview
- **Purpose**: Help entrepreneurs, retail operators, and investors assess commercial location viability before committing capital.
- **Engine**: 10,000-draw stochastic Monte Carlo simulation incorporating traffic intensity, pedestrian density, competitor density, and land zoning.
- **Location Coverage**: Prime commercial corridors in Bengaluru (Indiranagar, Koramangala, HSR Layout, Whitefield, JP Nagar, MG Road).
- **Supported Formats**: Café, Restaurant, Salon, Retail Store, Clinic, Warehouse / Dark Store.

## 📊 Live Simulation Preview
Below is a sample simulation execution output generated by the 10,000-draw Monte Carlo engine:

\`\`\`yaml
Business Format: Specialty Café
Target Corridor: Indiranagar 100ft Road, Bengaluru
Catchment Radius: 1.5 km
Assumed Capex: ₹15,00,000 (₹15 Lakhs)
Average Ticket Size: ₹250
Operating Hours: 12 hrs/day
Pedestrian Density: 1.2x (High)
Nearby Competitors: 3

Simulation Results:
  Location Score: 84 / 100
  Viability Probability: 78.4%
  Verdict: "Strong Viability — High footfall offset by high rent; maintain average order value above ₹220."

Financial Scenario Breakdown:
  Worst-Case (P10):
    Monthly Revenue: ₹3,40,000
    Monthly Profit: ₹38,000
    Break-Even Horizon: 28 Months
  Expected-Case (P50):
    Monthly Revenue: ₹5,80,000
    Monthly Profit: ₹1,12,000
    Break-Even Horizon: 14 Months
  Best-Case (P90):
    Monthly Revenue: ₹8,60,000
    Monthly Profit: ₹2,45,000
    Break-Even Horizon: 7 Months

Future Predictions:
  3-Month Projected Revenue: ₹4,20,000 / mo
  6-Month Projected Revenue: ₹5,10,000 / mo
  12-Month Projected Revenue: ₹6,20,000 / mo
  24-Month Projected Revenue: ₹7,80,000 / mo
  36-Month Projected Revenue: ₹9,40,000 / mo
\`\`\`

## 🗺️ Key Navigation Routes
- \`/\` — Interactive 3D landing page and value proposition
- \`/dashboard\` — Live Monte Carlo Location Decision Studio
- \`/analysis\` — Side-by-side corridor comparison & rankings
- \`/pricing\` — ₹99 Pro Tier features & transparent pricing
- \`/features\` — Detailed breakdown of simulation capabilities
- \`/how-it-works\` — Stochastic methodology and mathematical documentation
- \`/faq\` — Frequently Asked Questions
- \`/reports\` — Financial statement generation, CSV/PDF export
- \`/r/[token]\` — Immutable, read-only investor snapshots
- \`/billing\` — Pro Tier manual UPI QR payment & UTR submission
- \`/account\` — User profile and active session management
- \`/login\` — Account sign in
- \`/register\` — Account registration
- \`/admin\` — Administration governance and UTR approval queue

## 🔌 API Endpoints
- \`POST /api/auth/register\` — Create new account
- \`POST /api/auth/login\` — Authenticate and receive session cookie
- \`GET /api/auth/me\` — Active session profile
- \`GET /api/projects\` — List user workspaces
- \`POST /api/projects/:id/simulations\` — Execute 10,000-draw Monte Carlo simulation
- \`GET /api/billing/status\` — Check Pro entitlement
- \`GET /api/admin/dashboard\` — System analytics (Admin only)

## 📞 Contact & Support
- **Organization**: BUSINESS.IN Location Intelligence Team
- **Location**: Bengaluru, Karnataka, India
- **Support Email**: support@business.in
`;

  return new NextResponse(content, {
    status: 200,
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "public, max-age=86400",
    },
  });
}
