services:
  - type: web
    name: business-in
    runtime: node
    plan: free
    region: oregon
    rootDir: web
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: BETTER_AUTH_SECRET
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: NEXT_PUBLIC_APP_URL
        sync: false
