import type { Metadata } from "next";
import { Navbar } from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/Footer";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service — BUSINESS.IN",
  description: "Terms and conditions governing the use of the BUSINESS.IN decision simulation platform.",
  alternates: {
    canonical: "/terms",
  },
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#0A0A0A] text-white flex flex-col justify-between">
      <Navbar />
      
      <main className="max-w-4xl mx-auto px-6 py-16 space-y-12">
        <header className="space-y-4 text-center sm:text-left border-b border-white/10 pb-8">
          <span className="text-xs font-mono uppercase font-bold tracking-wider text-[#38BDF8] bg-[#38BDF8]/10 px-3 py-1 rounded-full border border-[#38BDF8]/30">
            Legal Agreement
          </span>
          <h1 className="text-3xl sm:text-5xl font-serif font-bold tracking-tight text-white">
            Terms of Service
          </h1>
          <p className="text-sm font-mono text-slate-300">
            Last updated: August 30, 2026 · Bengaluru Jurisdiction
          </p>
        </header>

        <section className="space-y-8 text-sm sm:text-base leading-relaxed text-slate-200">
          <div className="space-y-3">
            <h2 className="text-xl font-bold font-serif text-white">1. Acceptance of Terms</h2>
            <p>
              By accessing, browsing, or using the BUSINESS.IN platform, you acknowledge that you have read, understood, and agree to be bound by these Terms of Service and our Privacy Policy.
            </p>
          </div>

          <div className="space-y-3">
            <h2 className="text-xl font-bold font-serif text-white">2. Nature of Service & Decision Disclaimer</h2>
            <div className="p-4 rounded-xl bg-white/5 border border-white/15 text-slate-300">
              <strong className="text-[#FFD700]">IMPORTANT NOTICE:</strong> All revenue forecasts, break-even timelines, land availability grading, and Monte Carlo viability distributions generated by BUSINESS.IN are mathematical models and decision-support estimates. They do not constitute financial advice, guaranteed return on investment, or certified legal zoning clearance. Users are strongly advised to conduct independent on-site field surveys and title verification before signing commercial lease contracts.
            </div>
          </div>

          <div className="space-y-3">
            <h2 className="text-xl font-bold font-serif text-white">3. User Accounts & Security</h2>
            <p>
              You are responsible for maintaining the confidentiality of your login credentials. You agree to immediately notify BUSINESS.IN of any unauthorized access to your account.
            </p>
          </div>

          <div className="space-y-3">
            <h2 className="text-xl font-bold font-serif text-white">4. Pro Subscriptions & Payments</h2>
            <p>
              Pro upgrades (₹99 one-time launch fee) unlock unlimited scenario simulations and PDF/CSV investor exports. All payments processed via UPI with manual UTR verification are non-refundable once the digital entitlement is activated.
            </p>
          </div>

          <div className="space-y-3">
            <h2 className="text-xl font-bold font-serif text-white">5. Governing Law & Jurisdiction</h2>
            <p>
              These Terms shall be governed by and construed in accordance with the laws of India. Any disputes arising under these Terms shall be subject to the exclusive jurisdiction of the courts located in Bengaluru, Karnataka.
            </p>
          </div>
        </section>

        <div className="pt-8 border-t border-white/10 flex justify-between items-center text-xs text-slate-400">
          <Link href="/privacy" className="text-[#00FF85] hover:underline font-medium">
            View Privacy Policy &rarr;
          </Link>
          <Link href="/" className="text-slate-300 hover:text-white">
            Back to Home
          </Link>
        </div>
      </main>

      <Footer />
    </div>
  );
}
